version: "2"
services:
  trpgvore-back:
    container_name: trpgvore-back
    restart: always
    build: express/
    ports:
      - "3001:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"